### ISSUE TITLE
error

### ISSUE THREAD

**Issue by justadityabist** [ravibitsgoa/Parallelism-Intel-Arch-Assignments#1]
You have just put the exact file,and not the answer of the code(s).I am having problem in week 2 and 5,so was reffering to your work.Please do update the code.
thank you _/\_

**Comment by ravibitsgoa** [comment]
Can you please clarify what you mean by "answer of the codes"?
I think these are my solutions only.
But I took this course around 6 months back, hence my memory is a bit hazy.
For week 2, can you please take a look at this: https://github.com/ravibitsgoa/Parallelism-Intel-Arch-Assignments/blob/master/week2-integral/solutions/4-mpi/worker.cc

**Comment by Divyanshc10** [comment]
Hey man ! The "worker.cc" file of your week 5 is not being verified by the Coursera external tool. There must be an error in it ; can you please see to it and rectify if any. Tnx

**Comment by justadityabist** [comment]
the course has updated the question.Ravi did the course 6 monnths back and  thats why it will be showing verification error if you try his code.Its written in the important  notice in week5 assignment

**Comment by ltosh9802** [comment]
@justadityabist @Divyanshc10 @ravibitsgoa
Have you found out the solution of Week5? Can anybody please help me?

**Comment by neerajmahna** [comment]
I am also having issues with Week 5 solution. It is not passing verification step itself.

**Comment by ltosh9802** [comment]
@neerajmahna  I created a repo with the updated solution. Check it out!

**Comment by neerajmahna** [comment]
Any help in resolving issues in Week 5 assignment would be appreciable. I am stuck in following area:

	int right = rank+1, left = rank-1; 
	
	if(rank == world_size-1) 
	{ 

		MPI_Send(&d_t[start_segment], 1, MPI_FLOAT, left, 0, MPI_COMM_WORLD);
	
		MPI_Recv(&d_t[start_segment-1], 1, MPI_FLOAT, left, 0, MPI_COMM_WORLD, &status);
	
	
	} 
	else if(rank==0) 
	{ 
		
		MPI_Send(&d_t[last_segment -1], 1, MPI_FLOAT, right, 0, MPI_COMM_WORLD);
		MPI_Recv(&d_t[last_segment], 1, MPI_FLOAT, right, 0, MPI_COMM_WORLD, &status);
		} 
	else  
	{ 

		MPI_Send(&d_t[start_segment], 1, MPI_FLOAT, left, 0, MPI_COMM_WORLD);
	
		MPI_Recv(&d_t[start_segment-1], 1, MPI_FLOAT, left, 0, MPI_COMM_WORLD, &status);
	
		MPI_Send(&d_t[last_segment -1], 1, MPI_FLOAT, right, 0, MPI_COMM_WORLD);
		MPI_Recv(&d_t[start_segment], 1, MPI_FLOAT, right, 0, MPI_COMM_WORLD, &status);
	}
