### ISSUE TITLE
Missing Monte Carlo diffusion solution from Week 2.

### ISSUE THREAD

**Issue by 0ByteBlitz** [ravibitsgoa/Parallelism-Intel-Arch-Assignments#4]
Could you please update the vectorization code for Monte Carlo diffusion?

**Comment by ltosh9802** [comment]
I'm getting error in Week 5 as well. Have you done that @mukes1 ?

**Comment by 0ByteBlitz** [comment]
@ltosh9802 No, I haven't. I am on week 3 now. Did you complete week 2? If you have please share it.

**Comment by ltosh9802** [comment]
No bro I'm stuck on Week2 and Week5 only. Everything else is working.
